Merging Feature Branch Into Development
Kyle-Law/Restaurant-Page pull request #1
Opened 2020-08-13 11:07 UTC by Kyle-Law

Thank you for reviewing my projects, it's a basic Restaurant Web App powered by JavaScript. The entire DOM is generated by JavaScript.

- You can access the Live Version [HERE](https://rawcdn.githack.com/Kyle-Law/Restaurant-Page/31105de173296d30a1ebf2d5364fd32dcc7c5fbc/dist/index.html)
- it's a basic Restaurant Web App powered by JavaScript

2020-08-14 01:26 UTC, rOluochKe requested changes
Hello @Kyle-Law 
### You have done well so far :clap: However, you have a few issues to fix before your app can be approved.
- [ ] Remove all the commented lines in your codebase
- [ ] Separate the application logic from the dom manipulation
- [ ] In your package.json file, you can add the following lines in the script object. More automation
```
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional

```
- [ ] You can install `webpack-dev-server` and configure properly, this helps with the development environment
- [ ] Use a better font that is easily readable, you search from google fonts online library

### Make all these changes and submit for another code review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

2020-08-14 01:27 UTC, rOluochKe commented on src/index.js
> +    };
### Separate dom manipulation from the logic

2020-08-18 16:26 UTC, Kyle-Law commented
Good day! Thanks @rOluochKe for reviewing my project! Your recommendations have been implemented as followed:
- Unnecessary comments are removed
- more automation lines have been added into scripts tag in package.json
- A more readable font is used.
- Scripts have been modularized into 5 scripts

Live link is updated [HERE](https://rawcdn.githack.com/Kyle-Law/Restaurant-Page/9ad2ecacec36d866bff1cc6e161d7a8829daa8fc/dist/index.html)

Snapshots are updated as well:
![image](https://user-images.githubusercontent.com/55923773/90539103-00ad3100-e1b2-11ea-9eaa-e1395a22a501.png)

Thanks and looking forward to another review :)

2020-08-18 21:08 UTC, Forison approved these changes
## Status:: Approved✔️

# 🙋‍♂️ Kyle 

### Good job on addressing the issues raised in the previous review. Go ahead and merge the branch and proceed to the next task🤗.

**[OPTIONAL ]**

- Kindly make it a habit to always add a description to repositories you create on Github.

#### Happy coding👨‍💻

Addo Forison

2020-09-03 08:27 UTC, merged